/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Insurance;

import Business.Enterprise.InsuranceEnterprise;
import Business.Network.Network;
import Business.Organization.InsuranceOrganization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author amuly
 */
public class CustomerAnalyticsJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private InsuranceOrganization organization;
    private InsuranceEnterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    /**
     * Creates new form CustomerAnalyticsJPanel
     */
    public CustomerAnalyticsJPanel(JPanel userProcessContainer, InsuranceOrganization insuranceOrganization, InsuranceEnterprise insuranceEnterprise, UserAccount account, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization=insuranceOrganization;
        this.enterprise=insuranceEnterprise;
        this.userAccount=account;
        this.network = network;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 997, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
