/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Insurance;

import Business.Enterprise.CarRepairEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InsuranceEnterprise;
import Business.Network.Network;
import Business.Organization.InsuranceOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CarTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author amuly
 */
public class DefectiveCarsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private InsuranceOrganization organization;
    private InsuranceEnterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    /**
     * Creates new form DefectiveCarsJPanel
     */
    public DefectiveCarsJPanel(JPanel userProcessContainer,InsuranceOrganization insuranceOrganization, InsuranceEnterprise insuranceEnterprise, UserAccount account,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization=insuranceOrganization;
        this.enterprise=insuranceEnterprise;
        this.userAccount=account;
        this.network = network;
        populateTable();
        populateComboBox();
    }

     private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) workRequestsJTable.getModel();

        model.setRowCount(0);
        for (WorkRequest workRequest : organization.getWorkQueue().getWorkRequestList()) {
                Object[] row = new Object[5];
                row[0] = workRequest;
                row[1] = workRequest.getRequestDate();
                row[2] = workRequest.getReceiver();
                row[3] = workRequest.getStatus();
                Float cost = ((CarTestWorkRequest) workRequest).getCostOfRepair();
                row[4] = cost == null ? "Cost NA" : cost;
                model.addRow(row);
        }  
        
             workRequestsJTable.setDefaultRenderer(Object.class, new TableCellRenderer(){
             private DefaultTableCellRenderer DEFAULT_RENDERER =  new DefaultTableCellRenderer();

            @Override
            public Component getTableCellRendererComponent(JTable workRequestsJTable, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = DEFAULT_RENDERER.getTableCellRendererComponent(workRequestsJTable, value, isSelected, hasFocus, row, column);
                if(isSelected){
                    c.setBackground(Color.YELLOW);
                }else{
                if (row%2 == 0){
                    c.setBackground(Color.LIGHT_GRAY);

                }
                else {
                    c.setBackground(Color.WHITE);
                }
                }  

                       
                if(workRequestsJTable.getColumnModel().getColumn(column).getIdentifier().equals("Status")){//Here `Status` is column name
                     if(value.toString().equals("Sent to Insurance Company")){//Here `OK` is the value of row
                         c.setBackground(Color.green);                        
                        }  
                }
                
                return c;
            }

        });
        
        
        
        
        
    }
      
     
     private  void populateComboBox()
     {
        AssignRepairjComboBox.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
        {
            if(enterprise instanceof CarRepairEnterprise)
            {
                for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())        
                    {
                        for (UserAccount userAccount : organization.getUserAccountDirectory().getUserAccountList())
                        {
                            AssignRepairjComboBox.addItem(userAccount);
                        }
                    }
            }
        }
     }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestsJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        AssignRepairjComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        submitJPanel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        workRequestsJTable.setBackground(new java.awt.Color(153, 153, 255));
        workRequestsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Requested Date", "Repair Shop", "Status", "Repair Cost"
            }
        ));
        jScrollPane1.setViewportView(workRequestsJTable);

        jLabel1.setText("Assign to :");

        AssignRepairjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        AssignRepairjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignRepairjComboBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        submitJPanel.setText("Submit");
        submitJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJPanelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel2.setText("Assign Car Repair Shop");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(submitJPanel))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AssignRepairjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(768, 768, 768)
                        .addComponent(jLabel2)))
                .addGap(0, 549, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel2)
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssignRepairjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitJPanel)
                    .addComponent(jButton1))
                .addContainerGap(282, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void AssignRepairjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignRepairjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssignRepairjComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submitJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJPanelActionPerformed
       
        int selectedRow = workRequestsJTable.getSelectedRow();
        WorkRequest selectedworkRequest;
        UserAccount selectedReceiver;
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            selectedworkRequest = (WorkRequest) workRequestsJTable.getValueAt(selectedRow, 0);
            selectedReceiver = (UserAccount) AssignRepairjComboBox.getSelectedItem();
            
            
            String status = selectedworkRequest.getStatus();            
            if(status.equals("Assigned") || status.equals("Car repairing Done"))
            {
                JOptionPane.showMessageDialog(this, "Request already assigned or repaired", "Information", JOptionPane.INFORMATION_MESSAGE);
                selectedworkRequest = null;
            }    
            else
            {    
            selectedworkRequest.setReceiver(selectedReceiver);
            selectedReceiver.getWorkQueue().getWorkRequestList().add(selectedworkRequest);
            JOptionPane.showMessageDialog(this, "Request Sent", "Information", JOptionPane.INFORMATION_MESSAGE);
            selectedworkRequest.setStatus("Assigned");
            populateTable();
            }
            
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_submitJPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AssignRepairjComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitJPanel;
    private javax.swing.JTable workRequestsJTable;
    // End of variables declaration//GEN-END:variables
}
