/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Insurance;

import Business.Enterprise.InsuranceEnterprise;
import Business.Network.Network;
import Business.Organization.InsuranceOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author amuly
 */
public class InsuranceWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private InsuranceOrganization organization;
    private InsuranceEnterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    /**
     * Creates new form InsuranceWorkAreaJPanel
     */
    public InsuranceWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, InsuranceOrganization insuranceOrganization, InsuranceEnterprise insuranceEnterprise,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization=insuranceOrganization;
        this.enterprise=insuranceEnterprise;
        this.userAccount=account;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        analyticsJPanel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jButton1.setText("View Requests");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        analyticsJPanel.setText("Analytics");
        analyticsJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyticsJPanelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel1.setText("Insurance Work Area");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(865, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(773, 773, 773))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(analyticsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(790, 790, 790))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addGap(90, 90, 90)
                .addComponent(jButton1)
                .addGap(143, 143, 143)
                .addComponent(analyticsJPanel)
                .addContainerGap(381, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefectiveCarsJPanel defectiveCarsJPanel = new DefectiveCarsJPanel(userProcessContainer, organization, enterprise, userAccount,network);
        userProcessContainer.add("DefectiveCarsJPanel", defectiveCarsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);    
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void analyticsJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyticsJPanelActionPerformed
        CustomerAnalyticsJPanel customerAnalyticsJPanel = new CustomerAnalyticsJPanel(userProcessContainer, organization, enterprise, userAccount,network);
        userProcessContainer.add("CustomerAnalyticsJPanel", customerAnalyticsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);     // TODO add your handling code here:
    }//GEN-LAST:event_analyticsJPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyticsJPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
