/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Business.Pollution;

import Business.Enterprise.PollutionEnterprise;
import Business.Network.Network;
import Business.Organization.PollutionControlOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.CustomerWorkArea.SensorDataInputJPanel;

/**
 *
 * @author amuly
 */
public class PollutionWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PollutionControlOrganization organization;
    private PollutionEnterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    
    /**
     * Creates new form PollutionWorkAreaJPanel
     */
    
    
    public PollutionWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,PollutionControlOrganization organization,PollutionEnterprise enterprise,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.network = network;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pollutedCarsjButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pollutedCarsjButton.setText("View Cars Polluted");
        pollutedCarsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pollutedCarsjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(pollutedCarsjButton)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(pollutedCarsjButton)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void pollutedCarsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pollutedCarsjButtonActionPerformed

        ViewPollutionCarsJPanel viewPollutionCarsJPanel = new ViewPollutionCarsJPanel(userProcessContainer, userAccount, organization, enterprise, network);
        userProcessContainer.add("viewPollutionCarsJPanel", viewPollutionCarsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
// TODO add your handling code here:
    }//GEN-LAST:event_pollutedCarsjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pollutedCarsjButton;
    // End of variables declaration//GEN-END:variables
}
