/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CustomerWorkArea;

import Business.CarInspection.CarInspection;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InsuranceEnterprise;
import Business.Enterprise.GovernmentEnterprise;
import Business.Verifier.MyFloatVerifier;
import Business.Network.Network;
import Business.Organization.CustomerOrganization;
import Business.Organization.EmergencyOrganization;
import Business.Organization.InsuranceOrganization;
import Business.Organization.Organization;
import Business.Organization.PollutionControlOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CarTestWorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author amuly  
 */
public class SensorDataInputJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private CustomerOrganization organization;
    private InsuranceEnterprise enterprise;
    private UserAccount userAccount; 
    private Network network;
    /**
     * Creates new form SensorDataInputJPanel
     */
    public SensorDataInputJPanel(JPanel userProcessContainer,CustomerOrganization customerOrganization, InsuranceEnterprise insuranceEnterprise, UserAccount account, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization=customerOrganization;
        this.enterprise=insuranceEnterprise;
        this.userAccount=account;
        this.network = network;
        addVerifiers();
    }
    
    
        private void addVerifiers() {
        InputVerifier floatVerifier = new MyFloatVerifier();
        tyrePressureTextField.setInputVerifier(floatVerifier);
        brakeTextField.setInputVerifier(floatVerifier);
        alignTextField.setInputVerifier(floatVerifier);
        batteryTextField.setInputVerifier(floatVerifier);
        oilCheckTextField.setInputVerifier(floatVerifier);
        pollutionTextField.setInputVerifier(floatVerifier);  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tyrePressureTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        brakeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alignTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        batteryTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        oilCheckTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pollutionTextField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        latjTxtField = new javax.swing.JTextField();
        longjTxtField = new javax.swing.JTextField();
        emergencyjRadioBtn = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setText("Tyre Pressure");

        tyrePressureTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyrePressureTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Braking System");

        brakeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brakeTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Alignment");

        alignTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alignTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Battery");

        jLabel5.setText("Oil Check");

        jLabel7.setText("Pollution Level");

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel8.setText("SENSOR INPUT");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Coordinates");

        emergencyjRadioBtn.setText("Emergency");

        jLabel10.setText("%");

        jLabel11.setText("PSI");

        jLabel12.setText("degrees");

        jLabel13.setText("V");

        jLabel14.setText("mL");

        jLabel15.setText("pp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel6)
                        .addGap(295, 295, 295)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emergencyjRadioBtn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(backBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(submitBtn))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9))
                                        .addGap(157, 157, 157)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(brakeTextField)
                                                .addComponent(tyrePressureTextField)
                                                .addComponent(alignTextField)
                                                .addComponent(batteryTextField)
                                                .addComponent(oilCheckTextField)
                                                .addComponent(pollutionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(latjTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(longjTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(608, 608, 608)
                        .addComponent(jLabel8)))
                .addContainerGap(935, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {latjTxtField, longjTxtField});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tyrePressureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(brakeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(alignTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(batteryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oilCheckTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pollutionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(latjTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(longjTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(emergencyjRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(submitBtn))
                .addGap(256, 256, 256))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tyrePressureTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyrePressureTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tyrePressureTextFieldActionPerformed

    private void brakeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brakeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brakeTextFieldActionPerformed

    private void alignTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alignTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alignTextFieldActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed

    try{
    float tyrePressure = Float.parseFloat(tyrePressureTextField.getText());
    float brake = Float.parseFloat(brakeTextField.getText());
    float align = Float.parseFloat(alignTextField.getText());
    float battery = Float.parseFloat(batteryTextField.getText());
    float oil = Float.parseFloat(oilCheckTextField.getText());
    float pollution = Float.parseFloat(pollutionTextField.getText());
    float lattitude = Float.parseFloat(latjTxtField.getText());
    float longitude = Float.valueOf(longjTxtField.getText());
    boolean emerge = emergencyjRadioBtn.isSelected();  
    
    CarInspection carInspection = userAccount.getPerson().getCarInspectionHistory().createCarInspection();
    carInspection.setTyrePressure(tyrePressure);
    carInspection.setBrakingSys(brake);
    carInspection.setAlignment(align);
    carInspection.setBattery(battery);
    carInspection.setOilCheck(oil);
    carInspection.setPollutionLevel(pollution);
    carInspection.setTimestamp(new Date());
    carInspection.setLattitude(lattitude);
    carInspection.setLongitude(longitude);
    carInspection.setEmergency(false);
    
    if (emerge)
        carInspection.setEmergency(true);   
    else
        carInspection.setEmergency(false);
        
    
    
    if (brake <25 || tyrePressure <30 || align!= 0 || battery > 240)   //check the normal range
    {
        CarTestWorkRequest request = new CarTestWorkRequest();
        request.setRequestDate(new Date());
        request.setSender(userAccount);
        request.setCarInspection(carInspection);
        request.setStatus("Sent to Insurance Company");
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof InsuranceOrganization){
                org = organization;
                break;
            }
        }
        
        if (org!=null){
        org.getWorkQueue().getWorkRequestList().add(request);
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        
        JOptionPane.showMessageDialog(this, "Sensor input successfull", "Error", JOptionPane.INFORMATION_MESSAGE);
        clearFields();
    }
    
    
    if(pollution > 2)
    {
        CarTestWorkRequest pollutionReport = new CarTestWorkRequest();
        pollutionReport.setRequestDate(new Date());
        pollutionReport.setStatus("Reported to Pullution Dept");
        pollutionReport.setSender(userAccount);
        pollutionReport.setCarInspection(carInspection);
        

        
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
        {
            if (enterprise instanceof GovernmentEnterprise)
            {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
                        if(organization instanceof PollutionControlOrganization)
                            organization.getWorkQueue().getWorkRequestList().add(pollutionReport);
            }
        }
    }    
       
       if (emerge = true)
       {
             CarTestWorkRequest emergencyReport = new CarTestWorkRequest();
             emergencyReport.setRequestDate(new Date());
             emergencyReport.setStatus("Emergency found");
             emergencyReport.setSender(userAccount);
             emergencyReport.setCarInspection(carInspection);
             
        for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
        {
            if (enterprise instanceof GovernmentEnterprise)
            {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
                        if(organization instanceof EmergencyOrganization)
                            organization.getWorkQueue().getWorkRequestList().add(emergencyReport);
            }
        }
        
       }  
       }catch (Exception e) 
       {
           JOptionPane.showMessageDialog(this, "Wrong Input from sensor", "Error", JOptionPane.ERROR_MESSAGE);
       }    

// TODO add your handling code here:
    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    
    private void clearFields()
    {
        tyrePressureTextField.setText("");
        brakeTextField.setText("");
        alignTextField.setText("");
        batteryTextField.setText("");
        oilCheckTextField.setText("");
        pollutionTextField.setText("");
        latjTxtField.setText("");
        longjTxtField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alignTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField batteryTextField;
    private javax.swing.JTextField brakeTextField;
    private javax.swing.JRadioButton emergencyjRadioBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField latjTxtField;
    private javax.swing.JTextField longjTxtField;
    private javax.swing.JTextField oilCheckTextField;
    private javax.swing.JTextField pollutionTextField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField tyrePressureTextField;
    // End of variables declaration//GEN-END:variables
}
