/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Pollution;

import Business.Enterprise.GovernmentEnterprise;
import Business.Network.Network;
import Business.Organization.PollutionControlOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author amuly
 */
public class ViewPollutionCarsJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private PollutionControlOrganization organization;
    private GovernmentEnterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    
    /**
     * Creates new form ViewPollutionCarsJPanel
     */
    public ViewPollutionCarsJPanel(JPanel userProcessContainer,UserAccount userAccount,PollutionControlOrganization organization,GovernmentEnterprise enterprise,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.network = network;
        populateTable();
    }
    
    

     private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) pollutionJTable.getModel();

        model.setRowCount(0);
        for (WorkRequest workRequest : organization.getWorkQueue().getWorkRequestList()) {
                Object[] row = new Object[6];
                row[0] = workRequest;
                row[1] = workRequest.getStatus();
                row[2] = workRequest.getRequestDate();
                row[3] = workRequest.getCarInspection().getLattitude();
                row[4] = workRequest.getCarInspection().getLongitude();
                row[5] = workRequest.getCarInspection().getPollutionLevel();
                model.addRow(row);
        }  
        
            pollutionJTable.setDefaultRenderer(Object.class, new TableCellRenderer(){
            private DefaultTableCellRenderer DEFAULT_RENDERER =  new DefaultTableCellRenderer();

            @Override
            public Component getTableCellRendererComponent(JTable pollutionJTable, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = DEFAULT_RENDERER.getTableCellRendererComponent(pollutionJTable, value, isSelected, hasFocus, row, column);
                if(isSelected){
                    c.setBackground(Color.YELLOW);
                }else{
                if (row%2 == 0){
                    c.setBackground(Color.LIGHT_GRAY);

                }
                else {
                    c.setBackground(Color.WHITE);
                }
                }  
                return c;
            }

        });
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bckBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pollutionJTable = new javax.swing.JTable();
        mailjBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        bckBtn.setText("Back");
        bckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckBtnActionPerformed(evt);
            }
        });

        pollutionJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Owner", "Status", "Date", "Lattitude", "Longitude", "Pollution Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pollutionJTable);

        mailjBtn.setText("Mail");
        mailjBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailjBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel1.setText("View Polluting Cars");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(547, 547, 547)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bckBtn)
                                .addGap(527, 527, 527)
                                .addComponent(mailjBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(773, 773, 773)
                        .addComponent(jLabel1)))
                .addGap(51, 668, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bckBtn)
                    .addComponent(mailjBtn))
                .addContainerGap(324, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void bckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
// TODO add your handling code here:
    }//GEN-LAST:event_bckBtnActionPerformed

    private void mailjBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailjBtnActionPerformed

        int selectedRow = pollutionJTable.getSelectedRow();
        WorkRequest selectedworkRequest;
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            selectedworkRequest = (WorkRequest) pollutionJTable.getValueAt(selectedRow, 0);

        SendMailJPanel sendMailJPanel = new SendMailJPanel(userProcessContainer, userAccount, selectedworkRequest);
        userProcessContainer.add("SendMailJPanel", sendMailJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_mailjBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bckBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mailjBtn;
    private javax.swing.JTable pollutionJTable;
    // End of variables declaration//GEN-END:variables
}
